export enum ValidationEnumsDTOs {
    isString = 'isString',
    isNumber = 'isNumber',
    isBoolean = 'isBoolean',
    isDate = 'isDate',
    isArray = 'isArray',
    isObject = 'isObject',
    minLength = 'minLength',
    maxLength = 'maxLength',
    length = 'length',
    isEmail = 'isEmail',
    isUUID = 'isUUID',
    matches = 'matches',
    min = 'min',
    max = 'max',
    isPositive = 'isPositive',
    isNegative = 'isNegative',
    isInt = 'isInt',
    isDecimal = 'isDecimal',
    isNotEmpty = 'isNotEmpty',
}