import { ICatalogo } from "../../../modules/catalogo/interfaces/catalogo.interface";
import { IHistorialEntrenadoresInformacionPersonal } from "./historial-entrenadores/historial-entrenadores.ip.interface";
import { IHistorialEquiposInformacionPersonal } from "./historial-equipos/historial-equipos.ip.interface";
import { ILogrosClaveInformacionPersonal } from "./logros-clave/logros-clave.ip.interface";

export interface IInformacionPersonal {
    informacionPersonalId: number,
    fotoPerfilId: number,
    altura: number,
    peso: number,
    estatusBusquedaJugador: ICatalogo,
    medidaMano: number,
    largoBrazo: number,
    quienEres: string,
    fotoPerfilPublicUrl: string,
    alturaSaltoVertical?: number,
    distanciaSaltoHorizontal?: number,
    pesoBenchPress?: number,
    pesoSquats?: number,
    pesoPressMilitar?: number,
    pesoRepeticionBenchPress?: number,
    pesoRepeticionSquats?: number,
    pesoRepeticionPressMilitar?: number,
    tiempoDistanciaCienMts?: number,
    tiempoDistanciaUnKm?: number,
    tiempoDistanciaTresKm?: number,
    tiempoDistanciaCincoKm?: number,
    anioEmpezoAJugar: Date ,
    manoJuego: boolean ,
    posicionJuegoUno: ICatalogo ,
    posicionJuegoDos: ICatalogo ,
    clavas: boolean ,
    puntosPorJuego?: number ,
    asistenciasPorJuego?: number ,
    rebotesPorJuego?: number ,
    porcentajeTirosMedia?: number ,
    porcentajeTirosTres?: number ,
    porcentajeTirosLibres?: number ,
    desdeCuandoJuegas: Date ,
    horasEntrenamientoSemana?: number ,
    horasGymSemana?: number ,
    pertenecesClub: boolean ,
    nombreClub?: string ,
    historialEquipos?: IHistorialEquiposInformacionPersonal[] ,
    historialEntrenadores?: IHistorialEntrenadoresInformacionPersonal[] ,
    logrosClave?: ILogrosClaveInformacionPersonal[],
    objetivos?: string,
    valores?: string ,
}